[paths]
sample = "STR $.sample"
insert_mean = "FLOAT $.insert_size.mean"
insert_sd = "FLOAT $.insert_size.sd"
mapped_pairs = "INT $.mapped_pairs"
mapped_reads_properly_paired = "INT $.mapped_reads_properly_paired"
duplicate_reads = "INT $.duplicate_reads"

length_r1 = "INT $.read_1.read_length"
reads_r1 = "INT $.read_1.total_reads"
mapped_reads_r1 = "INT $.read_1.mapped_reads"
mapped_bases_r1 = "INT $.read_1.mapped_bases"
divergent_bases_r1 = "INT $.read_1.divergent_bases"
gc_bases_r1 = "INT $.read_1.gc_bases"
failed_reads_r1 = "INT $.read_1.qc_failed_reads"

length_r2 = "INT $.read_2.read_length"
reads_r2 = "INT $.read_2.total_reads"
mapped_reads_r2 = "INT $.read_2.mapped_reads"
mapped_bases_r2 = "INT $.read_2.mapped_bases"
divergent_bases_r2 = "INT $.read_2.divergent_bases"
gc_bases_r2 = "INT $.read_2.gc_bases"
failed_reads_r2 = "INT $.read_2.qc_failed_reads"

[variables]
bases_r1 = "length_r1 * reads_r1"
bases_r2 = "length_r2 * reads_r2"

[columns]
sample = "sample"
insert_mean = "insert_mean"
insert_sd = "insert_sd"
reads = "reads_r1 + reads_r2"
mapped_pairs = "(mapped_pairs * 1.0) / reads_r1"
proper_pairing = "(mapped_reads_properly_paired * 1.0) / reads_r1"
duplication = "(duplicate_reads * 1.0) / (reads_r1 + reads_r2)"
rmap_r1 = "(mapped_reads_r1 * 1.0) / reads_r1"
rmap_r2 = "(mapped_reads_r2 * 1.0) / reads_r2"
bmap_r1 = "(mapped_bases_r1 * 1.0) / bases_r1"
bmap_r2 = "(mapped_bases_r2 * 1.0) / bases_r2"
bdiv_r1 = "(divergent_bases_r1 * 1.0) / bases_r1"
bdiv_r2 = "(divergent_bases_r2 * 1.0) / bases_r2"
failed_r1 = "(failed_reads_r1 * 1.0) / reads_r1"
failed_r2 = "(failed_reads_r2 * 1.0) / reads_r2"
gc_r1 = "(gc_bases_r1 * 1.0) / bases_r1"
gc_r2 = "(gc_bases_r2 * 1.0) / bases_r2"
